# Generated by Django 3.2.5 on 2021-07-21 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=500)),
                ('region', models.CharField(blank=True, max_length=500, null=True)),
                ('business_names', models.CharField(max_length=500)),
                ('company_name', models.CharField(max_length=500)),
                ('rating', models.FloatField(blank=True, max_length=500, null=True)),
                ('review', models.CharField(blank=True, max_length=500, null=True)),
                ('category', models.CharField(blank=True, max_length=500, null=True)),
                ('address', models.CharField(blank=True, max_length=500, null=True)),
                ('latitude', models.FloatField(blank=True, max_length=500, null=True)),
                ('longitude', models.FloatField(blank=True, max_length=500, null=True)),
                ('phone', models.CharField(blank=True, max_length=500, null=True)),
                ('website', models.URLField(blank=True, max_length=500, null=True)),
                ('link_to_menu', models.CharField(blank=True, max_length=500, null=True)),
                ('location', models.CharField(blank=True, max_length=500, null=True)),
                ('critic_reviews', models.CharField(blank=True, max_length=500, null=True)),
                ('nearby', models.CharField(blank=True, max_length=500, null=True)),
                ('from_these_lists', models.CharField(blank=True, max_length=500, null=True)),
                ('reviews_sorting', models.CharField(blank=True, max_length=500, null=True)),
                ('product_title', models.TextField(blank=True, max_length=5000, null=True)),
                ('product_url', models.TextField(blank=True, max_length=5000, null=True)),
                ('photos_menu', models.TextField(blank=True, max_length=5000, null=True)),
                ('photos_owner', models.TextField(blank=True, max_length=5000, null=True)),
                ('photos_inside', models.TextField(blank=True, max_length=5000, null=True)),
                ('about', models.TextField(blank=True, max_length=5000, null=True)),
                ('about_details', models.TextField(blank=True, max_length=5000, null=True)),
                ('details', models.TextField(blank=True, max_length=5000, null=True)),
                ('facebook', models.URLField(blank=True, max_length=500, null=True)),
                ('instagram', models.URLField(blank=True, max_length=500, null=True)),
                ('linkedin', models.URLField(blank=True, max_length=500, null=True)),
                ('twitter', models.URLField(blank=True, max_length=500, null=True)),
                ('youtube', models.URLField(blank=True, max_length=500, null=True)),
                ('pinterest', models.URLField(blank=True, max_length=500, null=True)),
                ('service_options', models.TextField(blank=True, max_length=5000, null=True)),
                ('offerings', models.TextField(blank=True, max_length=5000, null=True)),
                ('dining_options', models.TextField(blank=True, max_length=5000, null=True)),
                ('amenities', models.TextField(blank=True, max_length=5000, null=True)),
                ('atmosphere', models.TextField(blank=True, max_length=5000, null=True)),
                ('crowd', models.TextField(blank=True, max_length=5000, null=True)),
                ('accessibility', models.TextField(blank=True, max_length=5000, null=True)),
                ('planning', models.TextField(blank=True, max_length=5000, null=True)),
                ('payments', models.TextField(blank=True, max_length=5000, null=True)),
                ('price', models.CharField(blank=True, max_length=500, null=True)),
                ('services', models.TextField(blank=True, max_length=5000, null=True)),
            ],
            options={
                'verbose_name_plural': 'Companies',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('reviewer_name', models.CharField(max_length=500)),
                ('reviewer_profile_link', models.URLField(max_length=500)),
                ('rating_stars', models.FloatField()),
                ('review_date', models.CharField(blank=True, max_length=500, null=True)),
                ('review_text', models.TextField(blank=True, max_length=5000, null=True)),
                ('review_pictures', models.TextField(blank=True, max_length=5000, null=True)),
                ('place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='place.place')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('asked_by', models.CharField(max_length=500)),
                ('answered_by', models.CharField(blank=True, max_length=500, null=True)),
                ('asked_by_profile', models.URLField(blank=True, max_length=500, null=True)),
                ('answered_by_profile', models.TextField(blank=True, max_length=5000, null=True)),
                ('question_date', models.CharField(blank=True, max_length=500, null=True)),
                ('question', models.URLField(blank=True, max_length=500, null=True)),
                ('answer', models.TextField(blank=True, max_length=5000, null=True)),
                ('place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='place.place')),
            ],
        ),
        migrations.CreateModel(
            name='Open',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('day', models.CharField(max_length=500)),
                ('open_interval', models.CharField(max_length=500)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='place.place')),
            ],
            options={
                'verbose_name_plural': 'Open hours',
            },
        ),
        migrations.CreateModel(
            name='Highlights',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('listing_name', models.CharField(max_length=500)),
                ('food_name', models.CharField(blank=True, max_length=500, null=True)),
                ('product_picture', models.TextField(blank=True, max_length=5000, null=True)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='place.place')),
            ],
            options={
                'verbose_name_plural': 'Highlights',
            },
        ),
    ]
