# Generated by Django 3.2.5 on 2021-07-21 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='business_names',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='place',
            name='company_name',
            field=models.CharField(max_length=1000),
        ),
    ]
