# Generated by Django 3.2.5 on 2021-07-21 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0002_auto_20210721_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
    ]
