# Generated by Django 3.2.5 on 2021-07-22 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0003_alter_question_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='city',
            field=models.CharField(db_index=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='place',
            name='price',
            field=models.CharField(blank=True, db_index=True, max_length=500, null=True),
        ),
    ]
